name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2

    - name: Generate Project Files
      run: ./scripts/Win-GenProjects.bat

    - name: Build Solution
      run: C:/"Program Files (x86)"/"Microsoft Visual Studio"/2019/BuildTools/MSBuild/Current/Bin/MSBuild.exe -property:Configuration=Release -maxCpuCount -verbosity:minimal -noLogo HyperEngine.sln