name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2

    - name: Generate Project Files
      run: ./scripts/Win-GenProjects.bat

    - name: Setup MSBuild
      id: setup_msbuild_path
      uses: ./

    - name: Build Solution
      run: msbuild -property:Configuration=Release -maxCpuCount -verbosity:minimal -noLogo HyperEngine.sln